const jobs = [
  {
    id: "job1",
    dp: "assets/images/photosnap.svg",
    company: "Photosnap",
    jobStatus: "NEW!",
    jobType: "Featured",
    jobRole: "Senior Frontend Developer",
    updated: "1d ago",
    employment: "Full Time",
    location: "USA only",
    data: {
      role: "Frontend",
      level: "Senior",
      languages: ["HTML", "CSS", "JavaScript"],
      tools: [],
    },
  },

  {
    id: "job2",
    dp: "assets/images/manage.svg",
    company: "Manage",
    jobStatus: "NEW!",
    jobType: "Featured",
    jobRole: "Fullstack Developer",
    updated: "1d ago",
    employment: "Part Time",
    location: "Remote",
    data: {
      role: "Fullstack",
      level: "Midweight",
      languages: ["Python"],
      tools: ["React"],
    },
  },

  {
    id: "job3",
    dp: "assets/images/account.svg",
    company: "Account",
    jobStatus: "NEW!",
    jobType: "",
    jobRole: "Junior Frontend Developer",
    updated: "2d ago",
    employment: "Contract",
    location: "USA only",
    data: {
      role: "Frontend",
      level: "Junior",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
    },
  },

  {
    id: "job4",
    dp: "assets/images/myhome.svg",
    company: "MyHome",
    jobStatus: "",
    jobType: "",
    jobRole: "Junior Frontend Developer",
    updated: "5d ago",
    employment: "Contract",
    location: "USA only",
    data: {
      role: "Frontend",
      level: "Junior",
      languages: ["CSS", "JavaScript"],
      tools: [],
    },
  },

  {
    id: "job5",
    dp: "assets/images/loop-studios.svg",
    company: "Loop Studios",
    jobStatus: "",
    jobType: "",
    jobRole: "Software Engineer",
    updated: "1w ago",
    employment: "Full Time",
    location: "Worldwide",
    data: {
      role: "Fullstack",
      level: "Midweight",
      languages: ["JavaScript"],
      tools: ["Sass", "Ruby"],
    },
  },

  {
    id: "job6",
    dp: "assets/images/faceit.svg",
    company: "FaceIt",
    jobStatus: "",
    jobType: "",
    jobRole: "Junior Backend Developer",
    updated: "2w ago",
    employment: "Full Time",
    location: "UK only",
    data: {
      role: "Backend",
      level: "Junior",
      languages: ["Ruby"],
      tools: ["RoR"],
    },
  },

  {
    id: "job7",
    dp: "assets/images/shortly.svg",
    company: "Shortly",
    jobStatus: "",
    jobType: "",
    jobRole: "Junior Developer",
    updated: "2w ago",
    employment: "Full Time",
    location: "Worldwide",
    data: {
      role: "Frontend",
      level: "Junior",
      languages: ["HTML", "JavaScript"],
      tools: ["Sass"],
    },
  },

  {
    id: "job8",
    dp: "assets/images/insure.svg",
    company: "Insure",
    jobStatus: "",
    jobType: "",
    jobRole: "Junior Frontend Developer",
    updated: "2w ago",
    employment: "Full Time",
    location: "USA only",
    data: {
      role: "Frontend",
      level: "Junior",
      languages: ["JavaScript"],
      tools: ["Vue", "Sass"],
    },
  },

  {
    id: "job9",
    dp: "assets/images/eyecam-co.svg",
    company: "Eyecam Co.",
    jobStatus: "",
    jobType: "",
    jobRole: "Full Stack Developer",
    updated: "3w ago",
    employment: "Full Time",
    location: "WorldWide",
    data: {
      role: "Fullstack",
      level: "Midweight",
      languages: ["JavaScript", "Python"],
      tools: ["Django"],
    },
  },

  {
    id: "job10",
    dp: "assets/images/the-air-filter-company.svg",
    company: "The Air Filter Company",
    jobStatus: "",
    jobType: "",
    jobRole: "Front-end Dev",
    updated: "1mo ago",
    employment: "Part Time",
    location: "Worldwide",
    data: {
      role: "Frontend",
      level: "Junior",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
    },
  },
];

export { jobs };
